apiVersion: v1
kind: Service
metadata:
  name: eks-webapp
  labels:
    app: eks-webapp
spec:
  selector:
    app: eks-webapp
  ports:
    - port: 80        # Service port
      targetPort: 8080  # Container port used in your Node.js app
  type: ClusterIP

